version: '3.8'

services:
  web:
    build: ./app
    container_name: ena_web
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:15
    container_name: ena_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ena}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-ena_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8082:8081"
    command: ["--listen=0.0.0.0", "--url", "postgres://ena:secret@db:5432/ena_db?sslmode=disable"]

volumes:
  db_data:
